### ISSUE TITLE
screenshot dragged into BeeRef is reflected horizontally

### ISSUE THREAD

**Issue by troy-lamerton** [rbreu/beeref#20] opened 2021-08-13 05:32 UTC
**Describe the bug**

Drag screenshot into BeeRef and it is reflected horizontally.

**To Reproduce**

MacOS
1. On MacOS, press Cmd+Shift+4 to take a screenshot of your screen
2. Click [done] button

Then open BeeRef
1. Drag Screenshot_x.png onto BeeRef
2. https://i.imgur.com/XYuo35u.png

**Expected behavior**

Png files added to BeeRef should render similarly to other image viewer apps.

**Screenshots**

https://i.imgur.com/XYuo35u.png

Was reproduced with this screenshot: [Screen Shot 2021-08-11 at 09 44 04](https://user-images.githubusercontent.com/13446008/129309480-3f2ad71a-f07b-42c2-88af-1f7eb8d37d36.png)

**Debug log:**

Not sure if needed or how to get this on MacOS. There is no Help menu on MacOS BeeRef.

**Comment by rbreu** [comment] 2021-08-13 13:22
Could you upload the screenshot that caused the issue as a zipped file? The problem is if you upload it as an image, most sites do some image conversion stuff with it that might remove the metadata that caused the issue. Maybe I can reproduce the issue on my machine if I got the screenshot exactly as it is on your machine.

**Comment by troy-lamerton** [comment] 2021-08-14 03:51
[Screen Shot 2021-08-11 at 09.44.04.png.zip](https://github.com/rbreu/beeref/files/6985854/Screen.Shot.2021-08-11.at.09.44.04.png.zip)

**Comment by andrsd** [comment] 2021-08-24 15:32
I ran into this as well. Basically any image I dropped into the main window is flipped (images saved from web or my own photos).

I tracked it down and attached patch fixes the issue:
```
--- a/beeref/fileio/image.py
+++ b/beeref/fileio/image.py
@@ -51,6 +51,8 @@ def exif_rotated_image(path=None):
 
     transform = QtGui.QTransform()
 
+    if orientation == exif.Orientation.TOP_LEFT:
+        return img.mirrored(horizontal=True, vertical=False)
     if orientation == exif.Orientation.TOP_RIGHT:
         return img.mirrored(horizontal=True, vertical=False)
     if orientation == exif.Orientation.BOTTOM_RIGHT:
```
However this would suggest that the orientation of the horizontal axis in Exif does not match what Qt thinks. So, definitely the final fix to apply. Just an insight on what I found out...

IDK if this is MacOS X specific. I can try on Windows. I don't have a linux machine around.

**Comment by rbreu** [comment] 2021-08-31 16:15
Orientation.TOP_LEFT means that the image is already in the correct orientation and shouldn't be transformed further. I can reproduce this problem on Linux and with images that don't have exif information in the first place, so that part of the code isn't even reached — the QtGui.QImage(path) at the beginning of the function returns the images flipped for some reason. 

I'll investigate this further.

**Comment by rbreu** [comment] 2021-08-31 17:02
To clarify, you are both using the dev/master version from github, right? Because I found a bug that I introduced when I added text items. I'm going to close this bug with the fix; if you have issues with the released 0.1.1 version, please reopen this bug.

**Comment by andrsd** [comment] 2021-08-31 17:05
Yes, I am using `main` since it has the Mac OS X tweaks. I can test with `0.1.1`.

**Comment by andrsd** [comment] 2021-08-31 17:07
Just tested with `0.1.1` and this is not happening there.

**Closed** 2021-08-31 17:12 UTC
Labels: bug
